### ISSUE TITLE
一些提供帮助的可能

### ISSUE THREAD

**Issue by XiaoyanLi1** [Nagi-ovo/BJUT-AI#1]
新老师一枚，上回参与了李老师的交流活动，虽然没时间参与整个project更新，但有问题我可以提供一点点帮助，比如课程前后的关联关系、如何完成目标导向的学习之类的，都可以放在这个project里。纯属出自兴趣和热情，有需要联系我xiaoyan.li@bjut.edu.cn

**Comment by Nagi-ovo** [comment]
谢谢老师！
本project计划在gitbook中记录第一届AI专业的学习历程和经验，仓库地址是：https://github.com/Nagi-ovo/ai-self-learning
已经创好群啦，现在把您再邀请加入GitHub Organization和协作者中，再次给感谢李老师的支持~
